Feat: Added options to have incremental or decremental buttons for the kind:manual
zwpaper/obsidian-progressbar pull request #14
Opened 2024-02-22 19:12 UTC by sukumar1210

- Added additional option for buttons for increasing or decreasing the value for the manual kind by 1.
- Added an id argument in order to identify and implement the button options.
- Also implemented the feature to have the ability to have multiple progressbar for the same context at different places and updating it at one place would update it at the other too.
- Updated README.md for new YAML configurations (id, buttons).
- Fixed a few typos in README.md.

resolves #13

2024-02-25 08:03 UTC, zwpaper requested changes
hi @sukumar1210 thanks so much for the PR, it mostly look great to me.

some comment appended above.

2024-02-25 08:03 UTC, zwpaper commented on README.md
> +buttons: true
how about we use `button` instead of `buttons`, for meaning it is a switch, not indicating there are 2 buttons

2024-02-25 11:52 UTC, sukumar1210 commented on main.ts
> +      console.log("hi");
Hey, by dropping this, you mean dropping the `console.log` and not the rest of the lines, right?
i understand dropping the `fontSize` for once, but dropping the line 171 does not make sense.

2024-02-25 12:51 UTC, sukumar1210 commented on main.ts
> +  if (blockTextYAML.value==0) {return;}
Actually, min is only being utilised for `day-custom` and not for the `manual` kind as far as i understood the code. For validating the min value it is first required that the manual kind implementation in the `newDayCustomProgressBar` method utilises the `min` first, which i don't see it doing.

Also if we were to utilise the min for the manual, where will the value be for the html progressbar element vary from? `0` to `max` or `min` to `max`? I just thought that the min value is only meant to be used with **day-custom**.

Kindly advise.

2024-02-25 13:02 UTC, sukumar1210 commented on main.ts
> +
i will do this manually for now, but what kind of formatting tools do you suggest or use?

2024-02-25 13:40 UTC, sukumar1210 commented on main.ts
> +  if (blockTextYAML.value==0) {return;}
i was meaning to ask question the relevance of min for the manual, i mean usually it would have ranged between `0` to `max`, but with the `min`, what ranges are we talking about? as min would introduce negative values (i don't know why anyone would want to use them) in the situation too, and for that we would need to handle it similarly to how you have handled the min value in the `day-custom` kind.

So i propose either of 2 things:
- remove the option of using min with manual
- or implement the same workaround as in `day-custom` in order to properly dill the html progressbar element if the min is negative.

2024-02-25 14:11 UTC, sukumar1210 commented on main.ts
> +  if (blockTextYAML.value==0) {return;}
I have modified the code so that it doesn't break on button press if the min is negative. But to display it properly it would require to do the shift in the value and max that you have done for `day-custom` in the `newProgressBar`, but that too in turn need some changes in the `newDayCustomProgressBar` method in order for that to keep working.

Do you wish me to do it in the following commit or should i just make the current code so that it does not break and implement the shifting of the values later in a different PR labelled as a [BUG FIX]

Kindly let me know how you would like me to proceed as i also wish to keep the commit history as relevant as i can. In my opinion it would be nicer if we went with the different PR labelled as [BUG FIX].

2024-02-25 17:20 UTC, sukumar1210 commented on main.ts
> +
addressed in 46d987cf8c6c6a2a190484efe12eceeaf8279c2d

2024-02-25 17:20 UTC, sukumar1210 commented on main.ts
> +
addressed in 46d987cf8c6c6a2a190484efe12eceeaf8279c2d

2024-02-25 17:20 UTC, sukumar1210 commented on main.ts
> +  });1
addressed in 46d987cf8c6c6a2a190484efe12eceeaf8279c2d

2024-02-25 17:20 UTC, sukumar1210 commented on main.ts
> +      console.log("hi");
addressed in 46d987cf8c6c6a2a190484efe12eceeaf8279c2d

2024-02-25 17:20 UTC, sukumar1210 commented on main.ts
> +  if (blockTextYAML.value==blockTextYAML.max) {return;}
addressed in 46d987cf8c6c6a2a190484efe12eceeaf8279c2d

2024-02-25 17:21 UTC, sukumar1210 commented on main.ts
> +       else {
addressed in 46d987cf8c6c6a2a190484efe12eceeaf8279c2d

2024-02-25 17:23 UTC, sukumar1210 commented on main.ts
> +       else {
addressed in 46d987cf8c6c6a2a190484efe12eceeaf8279c2d

2024-02-25 17:23 UTC, sukumar1210 commented on README.md
> +buttons: true
addressed in 46d987cf8c6c6a2a190484efe12eceeaf8279c2d

2024-02-25 17:24 UTC, sukumar1210 commented on main.ts
> +  if (blockTextYAML.value==0) {return;}
addressed in 46d987cf8c6c6a2a190484efe12eceeaf8279c2d

2024-02-29 04:16 UTC, zwpaper commented on main.ts
> +
I mostly use the LSP protocol, and for ts, I use https://github.com/typescript-language-server/typescript-language-server

2024-02-29 04:17 UTC, zwpaper commented on main.ts
> +      console.log("hi");
yes, I mean the line 174😂

2024-02-29 04:18 UTC, zwpaper approved these changes

2024-02-29 04:19 UTC, merged

2024-02-29 04:19 UTC, zwpaper commented
@sukumar1210 thanks so much for the contribution!